# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
es:
  languageCode: es
  contentDir: content/es
  title: Emiliano Lamas
  params:
    description: Emiliano Lamas es un estudiante de la Lic. en Economía por la UNLP.
  menu:
    main:
      - name: Inicio
        url: '#about'
        weight: 10
      - name: Contacto
        url: '#contact'
        weight: 20
      - name: CV
        url: ../uploads/CV - Emiliano Lamas.pdf
        weight: 30
